---
scope: foo
ec2_count: 2
ec2_scope : "{{ scope }}"
ec2_delete: foo
ec2_groupid : sg-0d86016242693e38f
ec2_subnetid : subnet-09ef163e228016359
ec2_lb: green
ec2_lb_target: green
ec2_region: eu-central-1a
ec2_vpc: vpc-0a2eaf21bc6aff140
ec2_size: t2.medium
ec2_ami: ami-ecc27c95
