---

- name: EAP actions
  hosts: "*eap"
  become: yes

  vars:
    rhn_username: "{{ rhsm_username }}"
    rhn_password: "{{ rhsm_password }}"
    rh_poolid: 8a85f98c651a8899016532fff64f29cd
  
  roles:
    - redhat-cop.jboss_common
    - redhat-cop.jboss_eap


  tasks:

    - name: Install EAP
      jboss:
        deploy_path: /opt/jboss-as/jboss-eap-7.1/standalone
        src: http://gitux01.openhybridcloud.io:8081/repository/coolstore-monolith-snapshots/com/redhat/coolstore/monolith/1.0.0-SNAPSHOT/monolith-1.0.0-20180828.131259-1.war
        deployment: coolstore
        state: present
