---
- name: EAP actions
  hosts: "{{ scope }}"
  become: yes

  vars:
    rhn_username: "{{ rhsm_username }}"
    rhn_password: "{{ rhsm_password }}"
    rh_poolid: "{{ rhpoolid }}"
  
  roles:
    - redhat-cop.jboss_common
    - jboss_eap


  tasks:

    - name: Install firewalld 
      yum:
        name: firewalld
        state: present

    - name: Open TCP port for EAP
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled 

    - name: Stop JBOSS
      service: 
        name: "{{ jboss_eap_service_file }}"
        state: stopped

    - name: Create jdbc folder
      file:
        path: /opt/jboss-as/jboss-eap-7.1/modules/com/microsoft/main/
        state: directory
        mode: 0775
        recurse: yes
        owner: jboss-as
        group: jboss_as

    - name: Create download temp folder
      file:
        path: /tmp/sqldriver
        state: directory
        mode: 0660

    - name: Get MS SQL jdbc driver
      unarchive:
        src: https://download.microsoft.com/download/2/F/C/2FC75210-EDDE-464C-8E54-45C0291032FF/sqljdbc_7.0.0.0_enu.tar.gz
        dest: /tmp/sqldriver
        remote_src: yes

    - name: Copy Driver to modules
      copy:
        src: /tmp/sqldriver/sqljdbc_7.0/enu/mssql-jdbc-7.0.0.jre8.jar
        dest: /opt/jboss-as/jboss-eap-7.1/modules/com/microsoft/main/mssql-jdbc-7.0.0.jre8.jar
        remote_src: yes
        owner: jboss-as
        group: jboss_as
        mode: 0664

    - name: Clean up download
      file: 
        name: /tmp/sqldriver
        state: absent 

    - name: Create the module.xml file
      copy:
        src: files/module.xml
        dest: /opt/jboss-as/jboss-eap-7.1/modules/com/microsoft/main/module.xml
        owner: jboss-as
        group: jboss_as
        mode: 0664

    - name: Customize Datasources
      template:
        src: templates/standalone.xml.j2
        dest: /opt/jboss-as/jboss-eap-7.1/standalone/configuration/standalone.xml
        owner: jboss-as
        group: jboss_as
        mode: 0664

    - name: Start JBOSS
      service: 
        name: "{{ jboss_eap_service_file }}"
        state: started

    - name: Get WAR
      get_url:
        url: "{{ artifact }}"
        dest: /tmp/coolstore.war
        force: yes

    - name: Install WAR
      jboss:
        deploy_path: /opt/jboss-as/jboss-eap-7.1/standalone/deployments/
        src: /tmp/coolstore.war
        deployment: ROOT.war
        state: present
      ignore_errors: yes

    - name: Ensure Nodes are present in F5 Load Balancer
      include_role:
        name: nehrman.ansible-role-f5
        tasks_from: add_node.yml
      delegate_to: localhost
      when: eap_ha








