---

- name: EAP actions
  hosts: "*eap"
  become: yes

  vars:
    rhn_username: "{{ rhsm_username }}"
    rhn_password: "{{ rhsm_password }}"
    rh_poolid: 8a85f98c651a8899016532fff64f29cd
  
  roles:
    - redhat-cop.jboss_common
    - redhat-cop.jboss_eap


  tasks:


    - name: Create jdbc folder
      file:
        path: /opt/jboss-as/jboss-eap-7.1/modules/com/microsoft/main/
        state: directory
        mode: 0755

    - name: Get MS SQL jdbc driver
      unarchive:
        src: https://download.microsoft.com/download/2/F/C/2FC75210-EDDE-464C-8E54-45C0291032FF/sqljdbc_7.0.0.0_enu.tar.gz
        dest: /opt/jboss-as/jboss-eap-7.1/modules/com/microsoft/main/
        remote_src: yes

    - name: Create the module.xml file
      copy:
        src: files/module.xml
        dest: /opt/jboss-as/jboss-eap-7.1/modules/com/microsoft/main/module.xml

    - name: Customize Datasources
      blockinfile:
        path: /opt/jboss-as/jboss-eap-7.1/standalone/configuration/standalone.xml 
              /opt/jboss-as/jboss-eap-7.1/standalone/configuration/standalone.xml
        block: |
          <datasource jta="true" jndi-name="java:jboss/datasources/CoolstoreDS" pool-name="coolstore-COOLSTORE" enabled="true" use-java-context="true">
              <connection-url>jdbc:sqlserver://localhost\monolith:1433</connection-url>
              <driver>sqlserver</driver>
              <security>
                  <user-name>{{ sqluser }}</user-name>
                  <password>{{ sqlpass }}</password>
              </security>
          </datasource>
        insertafter: "\s+\<datasources\>"

    - name: Customize Drivers
      blockinfile:
        path: /opt/jboss-as/jboss-eap-7.1/standalone/configuration/standalone.xml 
        block: |
          <driver name="sqlserver" module="com.microsoft">
            <driver-class>com.microsoft.sqlserver.jdbc.SQLServerDriver</driver-class>
            <xa-datasource-class>com.microsoft.sqlserver.jdbc.SQLServerXADataSource</xa-datasource-class>
          </driver>
        insertafter: "\s+<drivers\>"
      notify: Restart JBoss

    - name: Get WAR
      get_url:
        url: http://gitux01.openhybridcloud.io:8081/repository/coolstore-monolith-snapshots/com/redhat/coolstore/monolith/1.0.0-SNAPSHOT/monolith-1.0.0-20180926.122206-2.war
        dest: /tmp/coolstore.war
        force: yes

    - name: Install WAR
      jboss:
        deploy_path: /opt/jboss-as/jboss-eap-7.1/standalone/deployments/
        src: /tmp/coolstore.war
        deployment: ROOT.war
        state: present
