---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Create Database VM
      include_role:
        name: ec2
      vars:
        instance_tags: 
          - Name: "{{ scope }}"
          - Role: "database"
        ec2_count: 1
        ec2_size: t2_small
  
    - name: Create EAP VMs
      include_role:
        name: ec2
      vars:
        instance_tags: 
          Name: "{{ scope }}"
          Role: "jboss_eap"