---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Create Database VM
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Name: "{{ scope }}"
          Role: database
        ec2_count: 1
        ec2_size: t2.small
        ec2_ami: ami-02ace471
  
    - name: Create EAP VMs
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Name: "{{ scope }}"
          Role: eap
        ec2_size: t2.medium
        ec2_count: "{{ eap_ec2_count }}"
        ec2_ami: ami-0e12cbde3e77cbb98

#    - name: Refresh inventory 
#      meta: refresh_inventory

