---
- name: Create Azure Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Create DB in Azure
      include_role:
        name: azure
      vars:
        az_environment: "{{ scope }}"
        az_application: database
  
    - name: Create EAP VMs
      include_role:
        name: azure
      vars:
        az_environment: "{{ scope }}"
        az_application: eap


