---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Create Database VM
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Name: "{{ scope }}-mssql"
          Role: database
        ec2_count: 1
        ec2_size: t2.small
  
    - name: Create EAP VMs
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Name: "{{ scope }}"
          Role: jboss_eap
        ec2_size: t2.medium
        ec2_count: eap_ec2_count
