- name: Add EAP instances to load balancer
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Include tasks for load balancer control
      include_role:
        name: ec2
        tasks_from: ec2_loadbalancer.yml
      vars:
        ec2_lb_filters:
          "tag:Name": "{{ ec2_scope }}"
          "tag:Role":  "{{ ec2_instance_tags.Role }}"
          "instance-state-name": running
