---
- name: Install & Configure JBoss EAP
  hosts: tag_Role_eap:&tag_Scope_{{ customer }}
  gather_facts: yes
  become: yes

  vars:
    rhn_username: "{{ rhsm_username }}"
    rhn_password: "{{ rhsm_password }}"
    rh_poolid: "{{ rhpoolid }}"

  tasks:

    - name: Select Artifact 
      set_fact:
        artifact: "{{ artifact_store | regex_replace('/$','') }}/{{ war_name }}-{{ version }}.war"

    - name: Including EAP role 
      include_role:
        name: eap
      vars:
        eap_tags_for_database: "tag_Role_database:&tag_Name_{{scope}}"
        eap_tags_for_eap: "tag_Role_eap:&tag_Name_{{scope}}"



