---
- name: Install & Configure MS-SQL Express
  hosts: "{{ scope }}"
  become: True

  tasks: 

    - name: Register system to RHSM
      include_role:
        name: common
        tasks_from: register.yml
      when: eap_register

    - name: Install firewalld
      yum:
        name: firewalld
        state: latest

    - name: Start firewall service
      systemd: 
        name: firewalld 
        masked: no  
        enabled: yes
        state: started

    - name: Configure firewall for MS-SQL
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      with_items: 
        - 1433

    - name: Restart firewall service
      systemd: 
        name: firewalld 
        masked: no  
        enabled: yes
        state: restarted

    - name: Setup the MS-SQL Repository
      yum_repository:
        name: packages-microsoft-com-mssql-server-2017
        description: microsoft.com mssql-server-2017
        file: external_repos
        baseurl: https://packages.microsoft.com/rhel/7/mssql-server-2017/
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: yes

    - name: Install MS-SQL
      yum:
        name: mssql-server
        state: latest

    - name: Setup the MS-SQL Tools Repository
      yum_repository:
        name: packages-microsoft-com-prod
        description: microsoft.com packages prod
        file: external_repos
        baseurl: https://packages.microsoft.com/rhel/7/prod/
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: yes

    - name: Install MS-SQL utilities {{ packages }}
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - mssql-tools 
        - unixODBC-devel