
---

- name: EAP actions
  hosts: "{{ scope }}"
  become: yes

  tasks: 

    - set_fact:
        ansible_pkg_mgr: 'yum'
        jboss_java_pkg_name: 'java-1.8.0-openjdk-devel'
        jboss_eap_library_dest_dir: '/opt/jboss-as'
        jboss_eap_service_file: "jboss-standalone"

    - name: Stop JBOSS
      service: 
        name: "{{ jboss_eap_service_file }}"
        state: stopped

    - name: Remove Java
      action: "{{ ansible_pkg_mgr }} name={{ jboss_java_pkg_name }} state=absent"
  
    - name: Remove Unzip
      action: "{{ ansible_pkg_mgr }} name=unzip state=absent"

    - name: Remove EPEL Package
      action: "{{ ansible_pkg_mgr }} name='epel*' state=absent"
      changed_when: False

    - name: Remove JBOSS  
      file: 
        path: "{{ jboss_eap_library_dest_dir }}"
        state: absent

    - name: Remove JBoss EAP User
      user:
        name: 'jboss-as'
        state: absent 

    - name: Remove JBoss EAP Group
      group:
        name: 'jboss_as'
        state: absent

    # - name: Remove firewalld
    #   yum:
    #     name: firewalld
    #     state: absent

    - name: Clean up downloads
      file:
        name: "/tmp/{{ item }}"
        state: absent
      with_items:
        - epel-release-latest-7.noarch.rpm
        - jboss-eap-7.1.0.zip
        - jboss-eap-7.1.2-patch.zip
        - coolstore.war




    # - name: Undo HA config
    #   pass: 