- name: Verify that Red Hat Subscription Manager is present
  yum:
    name: subscription-manager
    state: present
  when: eap_register

- name: Register system into RHSM
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"