---
ec2_count: 2
scope : eap
ec2_action: create
ec2_groupid : sg-056f736390ec7b435
ec2_subnetid : subnet-0f78daed8116fef76
ec2_lb: green
ec2_lb_target: green
ec2_region: eu-west-1 
ec2_vpc: vpc-019b2b6b109d776dc
ec2_size: t2.medium